public_specs = "https://github.com/CocoaPods/Specs.git"

source "#{public_specs}"

install! 'cocoapods', :deterministic_uuids => false

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FFTest', :path => '../'

end
